version: '3'

services:
  influxdb:
    image: influxdb:1.2
    container_name: influxdb
    environment:
      - INFLUXDB_ADMIN_ENABLED=true
    ports:
      - "8086:8086"
      - "8083:8083"
    volumes:
      - ./volumes/influxdb:/var/lib/influxdb
    restart: always
